// Build styles.css — concatenates styles/*.css into root styles.css
// Usage: node build-styles.js

const fs = require('fs');
const path = require('path');

const STYLES_DIR = path.join(__dirname, 'styles');
const OUTPUT = path.join(__dirname, 'styles.css');

const FILES_IN_ORDER = ['core.css', 'ui.css', 'mobile.css'];

let combined = '/* AUTO-GENERATED by build-styles.js — do not edit directly */\n\n';

for (const file of FILES_IN_ORDER) {
  const filePath = path.join(STYLES_DIR, file);
  if (!fs.existsSync(filePath)) {
    console.error(`  Missing: styles/${file}`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  combined += `/* ── ${file} ────────────────────────────────────────────── */\n`;
  combined += content.trimEnd() + '\n\n';
}

fs.writeFileSync(OUTPUT, combined, 'utf8');
console.log(`  Built styles.css (${(combined.length / 1024).toFixed(1)} KB)`);
