  const DEFAULT_TEXT_STYLE_PRESETS = [
  {
    uid: "tsp-default",
    name: "Default",
    isDefault: true,
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 50,
    highlightBorderRadius: 8,
    highlightHorizontalPadding: 6,
    highlightVerticalPadding: 2,
    enableBorderThickness: false,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-sharp",
    isDefault: false,
    name: "Sharp",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 50,
    highlightBorderRadius: 0,
    highlightHorizontalPadding: 6,
    highlightVerticalPadding: 2,
    enableBorderThickness: false,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-round",
    isDefault: false,
    name: "Round",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 50,
    highlightBorderRadius: 8,
    highlightHorizontalPadding: 6,
    highlightVerticalPadding: 2,
    enableBorderThickness: false,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-pill",
    isDefault: false,
    name: "Pill",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 50,
    highlightBorderRadius: 9999,
    highlightHorizontalPadding: 10,
    highlightVerticalPadding: 2,
    enableBorderThickness: false,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-sharp-outline",
    isDefault: false,
    name: "Sharp Outlined",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 25,
    highlightBorderRadius: 0,
    highlightHorizontalPadding: 6,
    highlightVerticalPadding: 2,
    enableBorderThickness: true,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-round-outline",
    isDefault: false,
    name: "Round Outlined",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 25,
    highlightBorderRadius: 8,
    highlightHorizontalPadding: 6,
    highlightVerticalPadding: 2,
    enableBorderThickness: true,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-pill-outline",
    isDefault: false,
    name: "Pill Outlined",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 25,
    highlightBorderRadius: 9999,
    highlightHorizontalPadding: 10,
    highlightVerticalPadding: 2,
    enableBorderThickness: true,
    borderStyle: "full",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-dashed-under",
    isDefault: false,
    name: "Dashed Underline",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 0,
    highlightBorderRadius: 0,
    highlightHorizontalPadding: 0,
    highlightVerticalPadding: 0,
    enableBorderThickness: true,
    borderStyle: "bottom",
    borderLineStyle: "dashed",
    borderOpacity: 100,
    borderThickness: 2,
  },
  {
    uid: "tsp-double-under",
    isDefault: false,
    name: "Double Underline",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 0,
    highlightBorderRadius: 0,
    highlightHorizontalPadding: 0,
    highlightVerticalPadding: 0,
    enableBorderThickness: true,
    borderStyle: "bottom",
    borderLineStyle: "double",
    borderOpacity: 100,
    borderThickness: 3,
  },
  {
    uid: "tsp-under",
    isDefault: false,
    name: "Underline",
    styleType: "highlight",
    textColor: "currentColor",
    backgroundColor: "",
    backgroundOpacity: 0,
    highlightBorderRadius: 0,
    highlightHorizontalPadding: 0,
    highlightVerticalPadding: 0,
    enableBorderThickness: true,
    borderStyle: "bottom",
    borderLineStyle: "solid",
    borderOpacity: 100,
    borderThickness: 2,
  },
];

export const defaultSettings = {
  // legacy: wordColors map. New model below: wordEntries array
  wordColors: {},
  wordEntries: [],
  wordEntryGroups: [],
  blacklistEntryGroups: [],
  caseSensitive: false,
  matchType: "contains",
  quickStylesEnabled: true,
  oneTimeActionsFolded: false,
  defaultWordGroup: "",
  linkIdenticalMatchers: true,
  hiddenCommands: [],
  enabled: true,
  highlightStyle: "text",
  backgroundOpacity: 35, // percent
  highlightBorderRadius: 4, // px
  highlightHorizontalPadding: 4, // px
  highlightVerticalPadding: 0, // px
  enableBoxDecorationBreak: true, // Toggle for rounded corners on text wrapping
  enableBorderThickness: false, // Toggle for border on background highlights
  borderOpacity: 100, // percent (0-100)
  borderThickness: 2, // px (0-5)
  borderStyle: "full", // 'full', 'top', 'bottom', 'left', 'right', 'top-bottom', 'left-right', 'top-right', 'top-left', 'bottom-right', 'bottom-left'
  borderLineStyle: "solid",
  disabledFiles: [],
  customSwatches: [],
  // Default named swatches (editable via the Color Swatches modal)
  swatches: [
    { name: "Red", color: "#eb3b5a" },
    { name: "Orange", color: "#fa8231" },
    { name: "Yellow", color: "#e5a216" },
    { name: "Green", color: "#20bf6b" },
    { name: "Cyan", color: "#0fb9b1" },
    { name: "Blue", color: "#2d98da" },
    { name: "Dark Blue", color: "#3867d6" },
    { name: "Indigo", color: "#5454d0" },
    { name: "Purple", color: "#8854d0" },
    { name: "Light Purple", color: "#b554d0" },
    { name: "Neon Pink", color: "#e832c1" },
    { name: "Hot Pink", color: "#e83289" },
    { name: "Brown", color: "#965b3b" },
    { name: "Gray", color: "#8392a4" },
  ],
  // User-added custom swatches (separate from defaults)
  userCustomSwatches: [],
  disableToggleModes: {
    statusBar: false,
    command: false,
    ribbon: false,
  },
  enableAlwaysHighlight: false,
  enableAlwaysColor: true,
  partialMatch: true,
  blacklistWords: [],
  // New: pattern-capable blacklist entries
  blacklistEntries: [],
  enableBlacklistMenu: true,
  enableAddToExistingMenu: true,
  enableAlwaysColorTextMenu: true,
  hideInactiveGroupsInDropdowns: true,
  hideInactiveBlacklistGroupsInDropdowns: true,
  showWordGroupsInCommands: true,
  showBlacklistGroupsInCommands: true,
  symbolWordColoring: false,
  // Enable/disable regex support in the settings UI/runtime
  enableRegexSupport: false,
  // Opt-in: force full reading-mode render (WARNING: may freeze UI on large notes)
  forceFullRenderInReading: true,
  // Opt-in: extremely lightweight processing mode (experimental)
  extremeLightweightMode: false,
  // Opt-in: Smart Updates (Freeze non-active lines)
  enableSmartUpdates: false,
  // Opt-in: Word Completion Coloring (Wait for space)
  enableWordCompletionColoring: false,
  // Disable coloring in reading/preview mode (editor remains colored)
  disableReadingModeColoring: false,
  disableLivePreviewColoring: false,
  // Text & Background Coloring entries
  textBgColoringEntries: [],
  // Enable/disable Text & Background Coloring option in right-click menu
  enableTextBgMenu: true,
  // Use swatch names for coloring entries
  // useSwatchNamesForText: false,
  linkSwatchUpdatesToEntries: false,
  colorPickerMode: "both",
  advancedRules: [],
  pathRules: [],
  // Allow disabling regex safety checks (dangerous)
  disableRegexSafety: false,
  enableQuickColorHighlightOnce: false,
  enableQuickColorOnce: false,
  enableQuickHighlightOnce: false,
  quickHighlightStyleEnable: false,
  quickColorsEnabled: false,
  quickColorsApplyMode: "act",
  enableIndividualQuickStyleApplyMode: false,
  quickColors: [], // Array of { textColor, backgroundColor, uid }
  quickMenuColorsEnabled: false,
  quickMenuColors: [], // Array of swatch groups for quick menu
  quickStyles: [], // Array of objects { id, name, style }
  textStylePresets: DEFAULT_TEXT_STYLE_PRESETS, // Array of text style presets
  quickHighlightUseGlobalStyle: false,
  quickHighlightOpacity: 25,
  quickHighlightBorderRadius: 8,
  quickHighlightHorizontalPadding: 4,
  quickHighlightVerticalPadding: 0,
  quickHighlightEnableBorder: false,
  quickHighlightBorderStyle: "full",
  quickHighlightBorderOpacity: 100,
  quickHighlightBorderThickness: 1,
  quickHighlightBorderLineStyle: "solid",
  wordsSortMode: "last-added",
  blacklistSortMode: "last-added",
  pathSortMode: "last-added",
  language: "en",
  customSwatchesFolded: false,
  globalHighlightFolded: false,
  readingModeHighlightFilter: null, // null: show all, 'highlight': show only highlights, 'text': show only text colors
  entriesSearchLimit: 0,
  blacklistSearchLimit: 0,
  pathSearchLimit: 0,
  showColoringReasonOnHover: false, // Show tooltip on hover explaining why text is colored
  lightModeFixer: false,
  darkModeFixer: false,
  enableCustomCss: false,
  // Automatic backups
  autoBackupEnabled: false,
  autoBackupFolder: "",
  autoBackupInterval: 1,
  autoBackupUnit: "day", // "hour" | "day" | "week"
  autoBackupOverwrite: false, // true = keep one rolling file, false = timestamped files
  autoBackupLastRun: 0, // Unix timestamp (ms) of last successful backup
};
